package com.violas.wallet.common

// 常量
const val EXTRA_KEY_ACCOUNT_TYPE = "EXTRA_KEY_ACCOUNT_TYPE"
const val EXTRA_KEY_OPERATION_MODE = "EXTRA_KEY_OPERATION_MODE"
const val EXTRA_KEY_URL = "EXTRA_KEY_URL"
const val EXTRA_KEY_TITLE = "EXTRA_KEY_TITLE"
const val EXTRA_KEY_ACCOUNT_ID = "EXTRA_KEY_ACCOUNT_ID"
const val EXTRA_KEY_TOKEN = "EXTRA_KEY_TOKEN"
const val EXTRA_KEY_COUNTRY_AREA = "EXTRA_KEY_COUNTRY_AREA"
const val EXTRA_KEY_ACCOUNT_ADDRESS = "EXTRA_KEY_ACCOUNT_ADDRESS"
const val EXTRA_KEY_TOKEN_ADDRESS = "EXTRA_KEY_TOKEN_ADDRESS"
const val EXTRA_KEY_TOKEN_NAME = "EXTRA_KEY_TOKEN_NAME"
const val EXTRA_KEY_COIN_TYPES = "EXTRA_KEY_COIN_TYPES"
const val EXTRA_KEY_SSO_MSG = "EXTRA_KEY_SSO_MSG"