package com.violas.wallet.common

// 常量
const val EXTRA_KEY_ACCOUNT_TYPE = "EXTRA_KEY_ACCOUNT_TYPE"
const val EXTRA_KEY_OPERATION_MODE = "EXTRA_KEY_OPERATION_MODE"
const val EXTRA_KEY_URL = "EXTRA_KEY_URL"
const val EXTRA_KEY_TITLE = "EXTRA_KEY_TITLE"
const val EXTRA_KEY_ACCOUNT_ID = "EXTRA_KEY_ACCOUNT_ID"
const val EXTRA_KEY_TOKEN = "EXTRA_KEY_TOKEN"