package com.violas.wallet.common

// 常量
const val EXTRA_KEY_ACCOUNT_TYPE = "EXTRA_KEY_ACCOUNT_TYPE"
const val EXTRA_KEY_OPERATION_MODE = "EXTRA_KEY_OPERATION_MODE"
const val EXTRA_KEY_URL = "EXTRA_KEY_URL"
const val EXTRA_KEY_TITLE = "EXTRA_KEY_TITLE"
const val EXTRA_KEY_ACCOUNT_ID = "EXTRA_KEY_ACCOUNT_ID"
const val EXTRA_KEY_WALLET_ADDRESS = "EXTRA_KEY_WALLET_ADDRESS"
const val EXTRA_KEY_WALLET_TYPE = "EXTRA_KEY_WALLET_TYPE"
const val EXTRA_KEY_TOKEN_ADDRESS = "EXTRA_KEY_TOKEN_ADDRESS"
const val EXTRA_KEY_TOKEN_NAME = "EXTRA_KEY_TOKEN_NAME"
const val EXTRA_KEY_COIN_TYPES = "EXTRA_KEY_COIN_TYPES"

const val KEY_ONE = "KEY_ONE"
const val KEY_TWO = "KEY_TWO"
const val KEY_THREE = "KEY_THREE"
const val KEY_FOUR = "KEY_FOUR"
const val KEY_FIVE = "KEY_FIVE"

const val KEY_MSG_TYPE = "msg_type"
const val KEY_MSG_TXID = "msg_txid"


const val SYSTEM_ALBUM_DIR_NAME = "ViolasPay Photos"