package com.violas.wallet.common

// 常量
const val INTENT_KET_BACKUP_MNEMONIC_MODE = "INTENT_KET_BACKUP_MNEMONIC_MODE"
const val INTENT_KET_WALLET_SYSTEM = "INTENT_KET_WALLET_SYSTEM"
const val INTENT_KET_WALLET_NAME = "INTENT_KET_WALLET_NAME"
const val INTENT_KET_WALLET_PWD = "INTENT_KET_WALLET_PWD"

const val EXTRA_KEY_ACCOUNT_TYPE = "EXTRA_KEY_ACCOUNT_TYPE"
const val EXTRA_KEY_OPERATION_MODE = "EXTRA_KEY_OPERATION_MODE"
const val EXTRA_KEY_URL = "EXTRA_KEY_URL"
const val EXTRA_KEY_TITLE = "EXTRA_KEY_TITLE"