package com.violas.wallet.common

// 常量
const val INTENT_KET_BACKUP_MNEMONIC_MODE = "INTENT_KET_BACKUP_MNEMONIC_MODE"
const val INTENT_KET_WALLET_SYSTEM = "INTENT_KET_WALLET_SYSTEM"
const val INTENT_KET_WALLET_NAME = "INTENT_KET_WALLET_NAME"
const val INTENT_KET_WALLET_PWD = "INTENT_KET_WALLET_PWD"